// this code is autogenerated, do not check it into to your code repository

// ref lib/ex_pg_query.ex:9
const pg_query = @cImport(@cInclude("pg_query.h"));

pub const normalize = pg_query.pg_query_normalize;
